import Head from "next/head";

const DefaultLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>TXHT - Thanks Token</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container px-4 mx-auto">{children}</div>
    </>
  );
};

export default DefaultLayout;
