import Head from "next/head";
import Link from "next/link";

const DefaultLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>TXHT - Thanks Token</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="navbar">
        <div className="flex-1">
          <Link href="/">
            <a className="text-xl normal-case btn btn-ghost hover:bg-base-300">
              THXT
            </a>
          </Link>
        </div>
      </div>
      <div className="container mx-auto">{children}</div>
    </>
  );
};

export default DefaultLayout;
